<?php

namespace MGC\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * DedicatedServerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DedicatedServerRepository extends EntityRepository
{
	public function getForMap()
	{
		$locations = $this->findAll();
		
		$result = array();
		foreach($locations as $location)
		{
			$key = $location->getY().'-'.$location->getX();
			$result[$key] = $location;
		}
		
		return $result;
	}
	
	public function getAllPaginate($options = array())
	{
		$defaults = array(
			'page' => 1,
			'maxPerPage' => 10
		);
		
		$options = array_merge($defaults, $options);
		
		$queryBuilder = $this->createQueryBuilder('s')
							->select('s');
		
		$adapter = new DoctrineORMAdapter($queryBuilder->getQuery(), true);
		$pagerfanta = new Pagerfanta($adapter);
		$pagerfanta->setCurrentPage($options['page'], true, true);
		$pagerfanta->setMaxPerPage($options['maxPerPage']);
		
		return $pagerfanta;
	}
}
