<?php

namespace MGC\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GameBannerDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameBannerDocumentRepository extends EntityRepository
{
}
