<?php

namespace MGC\AdminBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * NewsCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsCategoryRepository extends EntityRepository
{
    public function getAllPaginate($options = array())
    {
        $defaults = array(
            'page' => 1,
            'maxPerPage' => 10,
            'forHomePage' => false
        );
    
        $options = array_merge($defaults, $options);
    
        $queryBuilder = $this->createQueryBuilder('n')
        ->select('n');
    
//         if($options['forHomePage']) {
//             $queryBuilder
//             ->where('n.publicationDate < :now')
//             ->andWhere('n.published = :status')
//             ->setParameter('status', true)
//             ->setParameter('now', date('Y-m-d H:i:s'));
//         }
    
//         $queryBuilder->orderBy('n.createdAt', 'DESC');
    
        $adapter = new DoctrineORMAdapter($queryBuilder->getQuery(), true);
        $pagerfanta = new Pagerfanta($adapter);
        $pagerfanta->setCurrentPage($options['page'], true, true);
        $pagerfanta->setMaxPerPage($options['maxPerPage']);
    
        return $pagerfanta;
    }
}
